puts "What state do you live in? Use the state's abbreviation."
state=gets.chomp.downcase
if state=="al"
    @rec = "You live in Alabama. A good pet shelter in your state is the Montgomery Humane Society."
  elsif state=="ak"
    @rec = "You live in Alaska. A good pet shelter in your state is the Gastineau Humane Society."
  elsif state=="az"
    @rec = "You live in Arizona. A good pet shelter in your state is the Halo Animal Rescue."
  elsif state=="ar"
    @rec = "You live in Arkansas. A good pet shelter in your state is the Humane Society of Pulaski County."
  elsif state=="ca"
    @rec = "You live in California. A good pet shelter in your state is the LA Animal Services."
  elsif state=="co"
    @rec = "You live in Colorado. A good pet shelter in your state is the Denver Animal Shelter."
  elsif state=="ct"
    @rec = "You live in Connecticut. A good pet shelter in your state is Friends of the New Haven Animal Shelter."
  elsif state=="de"
    @rec = "You live in Delaware. A good pet shelter in your state is the Faithful Friends Animal Society."
  elsif state=="fl"
    puts "You live in Florida. A good pet shelter in your state is the Humane Society of Greater Miami."
  elsif state=="ga"
    puts "You live in Georgia. A good pet shelter in your state is the Atlanta Humane Society."
  elsif state=="hi"
    puts "You live in Hawaii. A good pet shelter in your state is the Hawaiian Humane Society."
  elsif state=="id"
    puts "You live in Idaho. A good pet shelter in your state is the Idaho Humane Society."
  elsif state=="il"
    puts "You live in Illinois. A good pet shelter in your state is the Animal Protective League."
  elsif state=="in"
    puts "You live in Indiana. A good pet shelter in your state is IndyHumane - Humane Society of Indianapolis."
  elsif state=="ia"
    puts "You live in Iowa. A good pet shelter in your state is the Animal Rescue League of Iowa."
  elsif state=="ks"
    puts "You live in Kansas. A good pet shelter in your state is the Helping Hands Humane Society."
  elsif state=="ky"
    puts "You live in Kentucky. A good pet shelter in your state is the L.I.F.E. House for Animals."
  elsif state=="la"
    puts "You live in Louisiana. A good pet shelter in your state is the Companion Animal Alliance of Baton Rouge."
  elsif state=="me"
    puts "You live in Maine. A good pet shelter in your state is the Kennebec Valley Humane Society."
  elsif state=="md"
    puts "You live in Maryland. A good pet shelter in your state is the AACSPCA."
  elsif state=="ma"
    puts "You live in Massachusetts. A good pet shelter in your state is the Northeast Animal Shelter."
  elsif state=="mi"
    puts "You live in Michigan. A good pet shelter in your state is the Capital Area Humane Society."
  elsif state=="mn"
    puts "You live in Minnesota. A good pet shelter in your state is the Animal Humane Society."
  elsif state=="ms"
    puts "You live in Mississippi. A good pet shelter in your state is the Mississippi Animal Rescue League."
  elsif state=="mo"
    puts "You live in Missouri. A good pet shelter in your state is the Humane Society of Missouri."
  elsif state=="mt"
    puts "You live in Montana. A good pet shelter in your state is the Humane Society of Western Montana."
  elsif state=="ne"
    puts "You live in Nebraska. A good pet shelter in your state is the Capital Humane Society."
  elsif state=="nv"
    puts "You live in Nevada. A good pet shelter in your state is the Nevada Humane Society."
  elsif state=="nh"
    puts "You live in New Hampshire. A good pet shelter in your state is the Pope Memorial SPCA."
  elsif state=="nj"
    puts "You live in New Jersey. A good pet shelter in your state is the NJSPCA."
  elsif state=="nm"
    puts "You live in New Mexico. A good pet shelter in your state is the Santa Fe Animal Shelter & Humane Society."
  elsif state=="ny"
    puts "You live in New York. A good pet shelter in your state is the Animal Care Center of NYC."
  elsif state=="nc"
    puts "You live in North Carolina. A good pet shelter in your state is the Wake County Animal Shelter."
  elsif state=="nd"
    puts "You live in North Dakota. A good pet shelter in your state is the Central Dakota Humane Society."
  elsif state=="oh"
    puts "You live in Ohio. A good pet shelter in your state is the CHA Animal Shelter."
  elsif state=="ok"
    puts "You live in Oklahoma. A good pet shelter in your state is OKC Animal Welfare."
  elsif state=="or"
    puts "You live in Oregon. A good pet shelter in your state is the Oregon Humane Society."
  elsif state=="pa"
    puts "You live in Pennsylvania. A good pet shelter in your state is the Humane Society of Harrisburg Area."
  elsif state=="ri"
    puts "You live in Rhode Island. A good pet shelter in your state is Animal Rescue Rhode Island."
  elsif state=="sc"
    puts "You live in South Carolina. A good pet shelter in your state is Pawmetto Lifeline."
  elsif state=="sd"
    puts "You live in South Dakota. A good pet shelter in your state is the Hopeless to Homes Animal Rescue."
  elsif state=="tn"
    puts "You live in Tennessee. A good pet shelter in your state is Nashville Humane."
  elsif state=="tx"
    puts "You live in Texas. A good pet shelter in your state is the Houston SPCA."
  elsif state=="ut"
    puts "You live in Utah. A good pet shelter in your state is the Humane Society of Utah."
  elsif state=="vt"
    puts "You live in Vermont. A good pet shelter in your state is the Central Vermont Humane Society."
  elsif state=="va"
    puts "You live in Virginia. A good pet shelter in your state is the Richmond SPCA."
  elsif state=="wa"
    puts "You live in Washington. A good pet shelter in your state is Joint Animal Services."
  elsif state=="wv"
    puts "You live in West Virginia. A good pet shelter in your state is the Charlston Animal Society."
  elsif state=="wi"
    puts "You live in Wisconsin. A good pet shelter in your state is the Wisconsin Humane Society."
  elsif state=="wy"
    puts "You live in Wyoming. A good pet shelter in your state is the Black Dog Animal Rescue."
  else
    puts "Sorry, we don't recognize that state. We only accept states in America. Make sure you use the state's abbreviation. For example, mn for Minnesota. Try again."
  end